app/api/routes/aaa.py
from flask import Blueprint, render_template

aaa_bp = Blueprint('aaa_bp', __name__, url_prefix='/aaa')


@aaa_bp.route('/', methods=['GET'])
def add_job():
    """
    Render the add job page.

    Returns:
        Response: Rendered HTML page for adding a job.
    """
    return render_template('aaa.html')

app/api/routes/add_job_routes.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, flash
from app import db
from app.services.file_services.query_service import query, parse_response_to_dict
import os
import json

add_job_bp = Blueprint('add_job_bp', __name__, url_prefix='/add_job')


@add_job_bp.route('/', methods=['GET'])
def add_job():
    """
    Render the add job page with optional pre-filled data.

    Returns:
        Response: Rendered HTML page for adding a job.
    """
    job_title = request.args.get('job_title', '')
    job_number = request.args.get('job_number', '')
    job_description = request.args.get('job_description', '')
    requirements = request.args.get('requirements', '')
    opening_valid_date = request.args.get('opening_valid_date', '')

    return render_template(
        'add_job.html',
        job_title=job_title,
        job_number=job_number,
        job_description=job_description,
        requirements=requirements,
        opening_valid_date=opening_valid_date
    )


@add_job_bp.route('/job_content', methods=['POST'])
def job_content():
    """
    Handle the form submission for adding a job.

    Validate form inputs, check if the job exists, and either redirect to the confirmation page or show an error.

    Returns:
        Response: Redirects to the job confirmation page if successful,
                  or renders the add job page with an error message if unsuccessful.
    """
    job_title = request.form['job_title']
    job_description = request.form['job_description']
    job_number = request.form['job_number']
    requirements = request.form['requirements']
    date = request.form['opening_valid_date']
    print("date", date)

    # Validate that all fields are filled
    if not job_title or not job_description or not job_number:
        flash("All fields are required.", "error")
        return render_template('add_job.html')

    # Example check for existing job - Adjust this according to your database logic
    existing_job = db['job'].jobs.find_one({"job_number": job_number})
    if existing_job:
        flash("Job with this number already exists.", "error")
        return render_template('add_job.html')

    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    json_path = os.path.join(base_dir, 'static', 'json_templates', 'job_template.json')
    with open(json_path, 'r') as json_file:
        cv_data_template = json.load(json_file)

    query_request = (f"extract the following details from the text: {cv_data_template} \nMake sure your response is a "
                     f"valid json format")
    response = query(f"{job_title} \n {job_description} \n {job_number} \n {requirements}", query_request)
    extracted_details = parse_response_to_dict(response)

    company_name = extracted_details.get('organization_name')
    general_requirements = extracted_details.get('general_requirements', [])
    mandatory_requirements = extracted_details.get('mandatory_requirements', [])
    advantageous_requirements = extracted_details.get('advantageous_requirements', [])
    link_to_file = extracted_details.get('link_to_file', '')
    job_model = db['job']
    job_id = job_model.add_job(company_name, job_title, job_number, job_description, link_to_file, date,
                               mandatory_requirements,
                               general_requirements, advantageous_requirements)
    if not job_id:
        flash("The job could not be added to the database.", "error")
        return render_template('add_job.html')

    return redirect(url_for('add_job_bp.job_confirmation', job_title=job_title, job_number=job_number, description=job_description, requirements=requirements, date=date))


@add_job_bp.route('/job_confirmation')
def job_confirmation():
    """
    Render the job confirmation page after a job has been successfully created.

    Returns:
        Response: Rendered HTML page for job confirmation.
    """
    job_title = request.args.get('job_title')
    job_number = request.args.get('job_number')
    description = request.args.get('description')
    requirements = request.args.get('requirements')
    date = request.args.get('date')
    return render_template('job_confirmation.html', job_title=job_title, job_number=job_number, description=description, requirements=requirements, date=date)

app/api/routes/auth_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from app import db, oauth


auth_bp = Blueprint('auth_bp', __name__, template_folder='../templates', url_prefix='/auth')


@auth_bp.route('/', methods=['GET'])
def auth_home():
    return redirect(url_for('auth_bp.register'))


@auth_bp.route('/google_login')
def google_login():
    redirect_uri = url_for('auth_bp.google_callback', _external=True)
    print(f"Redirect URI: {redirect_uri}")  # Debugging line to ensure correct URI
    return oauth.google.authorize_redirect(redirect_uri)


@auth_bp.route('/google_callback')
def google_callback():
    print("---google callback function---")
    token = oauth.google.authorize_access_token()
    session['oauth_token'] = token  # Save the token to the session
    resp = oauth.google.get('userinfo')
    resp.raise_for_status()
    user_info = resp.json()
    user_model = db['organization']
    user = user_model.get_organization_by_email(user_info['email'])
    print("---user---", user)
    if not user:
        user_id = user_model.add_organization(email=user_info['email'], name=user_info['name'])
        user = {
            "_id": user_id,
            "email": user_info['email'],
            "name": user_info['name']
        }
    else:
        user_id = user['_id']
    if user:
        session['user_id'] = str(user_id)
        session['user_name'] = user_info['name']
        session['user_email'] = user_info['email']
        session['user_picture'] = user_info.get('picture')
    return redirect(url_for('dashboard_bp.dashboard'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        email = request.form.get('email')
        user_model = db['organization']
        if not user_model.is_valid_email(email):
            return """
                <script>
                    alert('Invalid email address');
                    window.location.href = '/auth/register';
                </script>
            """
        existing_user = user_model.get_organization_by_email(email)
        if existing_user:
            return """
                <script>
                    alert('User already exists');
                    window.location.href = '/auth/register';
                </script>
            """
        user_model.add_organization(username=username, email=email, password=password)
        return redirect(url_for('auth_bp.login'))
    return render_template('auth.html')


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        email = request.form.get('email')
        user_model = db['organization']
        user = user_model.get_organization_by_email(email)
        if user and user.verify_password(password):
            session['user_email'] = user.email
            session['username'] = user.username
            return redirect(url_for('main_bp.index'))
        return """
                <script>
                    alert('Invalid credentials');
                    window.location.href = '/auth/login';
                </script>
            """
    return render_template('auth.html')


@auth_bp.route('/logout')
def logout():
    token = session.get('oauth_token')
    if token:
        oauth.google.post(
            'https://accounts.google.com/o/oauth2/revoke',
            params={'token': token['access_token']},
            headers={'content-type': 'application/x-www-form-urlencoded'}
        )
    session.clear()
    # Redirect to Google logout URL to ensure account selection screen is shown
    return redirect(
        'https://accounts.google.com/Logout?continue=https://appengine.google.com/_ah/logout?continue=https'
        '://accounts.google.com/ServiceLogin?continue=https://localhost:5000/auth/login')

app/api/routes/full_resume.py
# app/api/routes/main_routes.py
import os
from flask import Blueprint, request, render_template, redirect, url_for, send_from_directory, current_app, flash
from werkzeug.utils import secure_filename
import pypandoc

full_resume_bp = Blueprint('full_resume_bp', __name__, url_prefix='/full_resume')


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in {'pdf', 'doc', 'docx', 'txt'}


@full_resume_bp.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            file_extension = filename.rsplit('.', 1)[1].lower()

            if file_extension == 'txt':
                with open(os.path.join(current_app.config['UPLOAD_FOLDER'], filename), 'r') as f:
                    file_content = f.read()
            elif file_extension in {'doc', 'docx'}:
                file_content = pypandoc.convert_file(os.path.join(current_app.config['UPLOAD_FOLDER'], filename),
                                                     'html')
            else:
                file_content = None

            return render_template('full_resume.html', filename=filename, file_extension=file_extension,
                                   file_content=file_content)

    return render_template('full_resume.html')


@full_resume_bp.route('/display/<filename>')
def display_file(filename):
    return send_from_directory(current_app.config['UPLOAD_FOLDER'], filename)

app/api/routes/matching_routes.py
from flask import Blueprint, render_template
from app import db

matching_bp = Blueprint('matching_bp', __name__, url_prefix='/matching')


@matching_bp.route('/', methods=['GET'])
def list_matches():
    """
    Renders the matching list page with match data.

    This route fetches all matches from the database, retrieves associated job and candidate details,
    and renders the 'matching.html' template with this data.

    Returns:
        Response: The rendered matching list HTML page with match data.
    """
    matches = db['match'].matches.find()
    matches_list = list(matches)
    updated_matches_list = []
    for match in matches_list:
        job = db['job'].get_job(match['job_id'])
        candidate = db['candidate'].get_candidate(match['candidate_id'])
        match = {
            "candidate_id": match['candidate_id'],
            "candidate_name": candidate['name'],
            "job_id": match['job_id'],
            "job_number": job['job_number'],
            "general_requirements": match['general_requirements'],
            "mandatory_requirements": match['mandatory_requirements'],
            "advantageous_requirements": match['advantageous_requirements'],
            "final_score": match['final_score'],
            "general_system_comments": match['general_system_comments'],
        }
        updated_matches_list.append(match)

    return render_template('matching.html', resumes=updated_matches_list)

app/api/routes/mishra_number.py
from flask import Blueprint, render_template

mishra_number_bp = Blueprint('mishra_number_bp', __name__, url_prefix='/mishra_number')


@mishra_number_bp.route('/', methods=['GET'])
def mishra_number():
    """
    Render the add job page.

    Returns:
        Response: Rendered HTML page for adding a job.
    """
    return render_template('mishra_number.html')

app/api/routes/nav.py
from flask import Blueprint, render_template


nav_bp = Blueprint('nav_bp', __name__, template_folder='../templates', url_prefix='/')


@nav_bp.route('/', methods=['GET'])
def nav():
    return render_template("nav.html")

app/api/routes/nav_bar.py
# from flask import Blueprint, render_template
#
# navbar_bp = Blueprint('navbar_bp', __name__, template_folder='../templates', url_prefix='/')
#
#
# @navbar_bp.route('/')
# def navbar():
#     return render_template('navbar.html')

app/api/routes/resume.py
from flask import Blueprint, render_template, request
from app import db
from bson.objectid import ObjectId

resume_bp = Blueprint('resume_bp', __name__, url_prefix='/resume')


@resume_bp.route('/', methods=['GET'])
def show_resume():
    resume_id = request.args.get('resume_id')

    if not resume_id:
        return "No resume ID provided", 400

    resume = db['resume'].resumes.find_one({"_id": ObjectId(resume_id)})

    extract_resume = resume.get('extract_resume', {})

    # Breaking down the dictionary for easy access in the template
    personal_info = extract_resume.get('personal_information', {})
    summary = extract_resume.get('summary', '')
    experience = extract_resume.get('professional_experience', [])
    education = extract_resume.get('education', [])
    skills = extract_resume.get('skills', [])
    tools = extract_resume.get('tools', [])
    certifications = extract_resume.get('certifications', [])
    projects = extract_resume.get('projects', [])
    languages = extract_resume.get('languages', [])
    publications = extract_resume.get('publications', [])
    volunteer_experience = extract_resume.get('volunteer_experience', [])

    # Pass the data to the template
    return render_template("resume.html",
                           personal_info=personal_info,
                           summary=summary,
                           experience=experience,
                           education=education,
                           skills=skills,
                           tools=tools,
                           certifications=certifications,
                           projects=projects,
                           languages=languages,
                           publications=publications,
                           volunteer_experience=volunteer_experience)

app/api/routes/resume_list.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app import db

resume_list_bp = Blueprint('resume_list_bp', __name__, url_prefix='/resume_list')


@resume_list_bp.route('/', methods=['GET'])
def resume_list():
    resumes = db['resume'].resumes.find()
    all_resumes = list(resumes)
    processed_resumes = []
    print("all_resumes", all_resumes)
    for resume in all_resumes:
        print("in for statement", str(resume.get('candidate_id')))
        candidate = db['candidate'].get_candidate(str(resume.get('candidate_id')))
        job = db['job'].get_job(str(resume.get('job_id')))

        processed_resumes.append({
            'id': str(resume.get('_id')),  # Add the resume ID here
            'name': candidate['name'],
            'job_number': job['job_number'],
            'hasNotification': False,
            'resume_link': url_for('resume_bp.show_resume', resume_id=str(resume.get('_id')))  # Updated link
        })
        print("all_resumes", all_resumes[0])

    return render_template('resume_list.html', resumes=processed_resumes)


@resume_list_bp.route('/delete_resume/<resume_id>', methods=['POST'])
def delete_resume(resume_id):
    job_id = request.form['job_id']
    db['resume'].delete_resume(resume_id)
    return redirect(url_for('resume_list_bp.resume_list', job_id=job_id))

app/api/routes/resume_routes.py
from flask import Blueprint, redirect, render_template, request, jsonify, url_for
import json
from app import db

resume_list_bp = Blueprint('resume_list_bp', __name__, url_prefix='/resume_list')


@resume_list_bp.route('/', methods=['GET'])
def resume_list():
    jobs = db['job'].jobs.find()
    job_list = list(jobs)
    selected_job = None
    resumes = []

    job_id = request.args.get('job_id')
    if job_id:
        selected_job = db['job'].get_job(job_id)
        resumes = db['resume'].get_resumes_by_job_id(job_id)

    return render_template('resume_list.html', jobs=job_list, resumes=list(resumes), selected_job=selected_job)


@resume_list_bp.route('/view_resume/<resume_id>', methods=['GET'])
def view_resume(resume_id):
    resume = db['resume'].get_resume(resume_id)
    if resume:
        return jsonify({'resume_text': resume['extract_resume']})
    return jsonify({'error': 'Resume not found'}), 404


@resume_list_bp.route('/view_resume_link/<resume_id>', methods=['GET'])
def view_resume_link(resume_id):
    resume = db['resume'].get_resume(resume_id)
    if resume:
        return jsonify({'resume_link': resume['resume_link']})
    return jsonify({'error': 'Resume not found'}), 404


@resume_list_bp.route('/edit_resume/<resume_id>', methods=['POST'])
def edit_resume(resume_id):
    updated_data = request.get_json()
    extract_resume_data = json.loads(updated_data['extract_resume'])
    result = db['resume'].update_resume(resume_id, extract_resume_data)
    if result.modified_count == 1:
        return jsonify({'success': True, 'message': 'Resume updated successfully.'})
    else:
        return jsonify({'success': False, 'message': 'Resume update failed.'})

app/api/templates/add_job.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Job Opening</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #fff;
            font-family: 'Urbanist', sans-serif;
        }

        .container {
            margin-top: 50px;
            text-align: center;
        }

        .content {
            margin-left: 80px;
            padding: 20px;
        }

        .form-container {
            background-color: white;
            padding: 30px;
            border-radius: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 823px;
            margin: auto;
            position: relative;
        }

        .form-control {
            display: block;
            width: 100%;
            padding: .375rem .75rem;
            font-size: 1rem;
            font-weight: 400;
            line-height: 1.5;
            color: #212529;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #ced4da;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            border-radius: .25rem;
            transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
            border: 1px solid #7879F1;
        }

        .btn-pink {
            background-color: #FF4081;
            color: white;
            border: none;
            border-radius: 40px;
            font-size: 20px;
            font-weight: 700;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 300px;
            height: 51px;
            padding: 0;
            position: absolute;
            bottom: -50px;
            right: 50%;
            transform: translateX(50%);
            gap: 10px;
        }

        .btn-pink:hover {
            background-color: #e53770;
        }

        .btn-pink .btn-icon {
            width: 21px;
            height: 21px;
            fill: #FFF;
        }

        .form-label {
            color: #150F6B;
            font-weight: bold;
            text-align: left;
        }

        h2 {
            color: #FF4081;
            font-weight: bold;
            text-align: left;
            margin-left: 230px;
        }

        .form-row {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
        }

        .form-column {
            display: flex;
            flex-direction: column;
            gap: 20px;
            flex: 1;
        }

        .form-group {
            flex: 1;
            min-width: 280px;
            text-align: left;
        }

        .form-group-full {
            width: 100%;
        }

    </style>
</head>

<body>
{% include 'nav.html' %}
    <div class="content container">
        <h2>Create new job opening</h2>
        <div class="form-container">
            <form action="{{ url_for('add_job_bp.job_content') }}" method="post">
                <div class="form-row">
                    <div class="form-column">
                        <div class="form-group">
                            <label for="jobTitle" class="form-label">Job title</label>
                            <input type="text" class="form-control" id="jobTitle" name="job_title" value="{{ request.args.get('job_title', '') }}">
                        </div>
                        <div class="form-group">
                            <label for="jobNumber" class="form-label">Job number</label>
                            <input type="text" class="form-control" id="jobNumber" name="job_number" value="{{ request.args.get('job_number', '') }}">
                        </div>
                        <div class="form-group form-group-full">
                            <label for="jobDescription" class="form-label">Description</label>
                            <textarea class="form-control" id="jobDescription" name="job_description" rows="3">{{ request.args.get('job_description', '') }}</textarea>
                        </div>
                    </div>
                    <div class="form-column">
                        <div class="form-group">
                            <label for="requirements" class="form-label">Requirements</label>
                            <textarea class="form-control" id="requirements" name="requirements" rows="3">{{ request.args.get('requirements', '') }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="opening_valid_date" class="form-label">Opening valid date</label>
                            <input type="date" class="form-control" id="opening_valid_date" name="opening_valid_date" placeholder="DD/MM/YYYY" value="{{ request.args.get('opening_valid_date', '') }}">
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-pink">
                    Publish new role <i class="fas fa-star btn-icon"></i>
                </button>
            </form>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"></script>
</body>

</html>

app/api/templates/full_resume.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice Display</title>
    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            width: 100%;
            overflow: hidden;
            display: flex;
            flex-direction: column;
        }

        .nav-container {
            width: 60px; /* Adjust width based on your nav bar's width */
            background-color: #2E3B4E;
            height: 100%;
            position: fixed;
            top: 0;
            left: 0;
        }

        .content-container {
            flex-grow: 1;
            width: calc(100% - 60px); /* Adjust to subtract the nav width */
            height: 100%;
            margin-left: 60px; /* Adjust to account for nav width */
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
        }

        .pdf-container {
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
        }

        .pdf-container embed, .pdf-container object, .pdf-container iframe {
            width: 100%;
            height: 100%;
            border: none;
            display: block;
            background-color: #ccc; /* Grey background for better contrast */
        }

    </style>
</head>
<body>
    <div class="nav-container">
        {% include 'nav.html' %}
    </div>
    <div class="content-container">
        {% if not filename %}
            <!-- File upload form -->
            <form class="upload-form" action="{{ url_for('full_resume_bp.index') }}" method="post" enctype="multipart/form-data">
                <input type="file" name="file" required>
                <button type="submit">Upload</button>
            </form>
        {% else %}
            <!-- Display the uploaded file -->
            {% if file_extension == 'pdf' %}
                <div class="pdf-container">
                    <embed src="{{ url_for('full_resume_bp.display_file', filename=filename) }}#toolbar=0" type="application/pdf" />
                </div>
            {% elif file_extension == 'txt' %}
                <div class="pdf-container">
                    <pre class="full-screen">{{ file_content }}</pre>
                </div>
            {% elif file_extension in ['doc', 'docx'] %}
                <div class="pdf-container">
                    <div class="full-screen">{{ file_content|safe }}</div>
                </div>
            {% else %}
                <p>File type not supported.</p>
            {% endif %}
        {% endif %}
    </div>
</body>
</html>

app/api/templates/navbar.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <title>Navigation Bar</title>-->
<!--    &lt;!&ndash; Include Bootstrap CSS for styling (optional) &ndash;&gt;-->
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">-->
<!--    <style>-->
<!--        .navbar-nav .nav-item .nav-link img {-->
<!--            border-radius: 50%;  /* Makes the image round */-->
<!--            height: 24px;        /* Adjust the height to make it smaller */-->
<!--            width: 24px;         /* Adjust the width to make it smaller */-->
<!--            object-fit: cover;   /* Ensures the image covers the given dimensions */-->
<!--            cursor: pointer;     /* Changes cursor to pointer to indicate it's clickable */-->
<!--        }-->
<!--        .navbar-nav .nav-item.d-flex {-->
<!--            align-items: center;-->
<!--        }-->
<!--        .dropdown-menu {-->
<!--            right: 0; /* Align the dropdown to the right */-->
<!--            left: auto;-->
<!--            padding: 10px;-->
<!--            min-width: 200px;-->
<!--        }-->
<!--        .dropdown-item {-->
<!--            display: flex;-->
<!--            align-items: center;-->
<!--        }-->
<!--        .dropdown-item .icon {-->
<!--            margin-right: 10px;-->
<!--        }-->
<!--    </style>-->
<!--</head>-->
<!--<body>-->
<!--    <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--        <a class="navbar-brand" href="#">MyApp</a>-->
<!--        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->
<!--        <div class="collapse navbar-collapse" id="navbarNav">-->
<!--            <ul class="navbar-nav">-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{{ url_for('dashboard_bp.dashboard') }}" method="GET">Dashboard</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{{ url_for('add_job_bp.add_job') }}" method="GET">Add Job</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{{ url_for('jobs_list_bp.jobs_list') }}" method="GET">Upload Resume</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{{ url_for('monitoring_bp.monitoring') }}" method="GET">Folder Listening</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{{ url_for('resume_list_bp.resume_list') }}" method="GET">Resumes List</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{{ url_for('matching_bp.list_matches') }}" method="GET">Matches</a>-->
<!--                </li>-->
<!--            </ul>-->
<!--            <ul class="navbar-nav ml-auto">-->
<!--                {% if session['user_email'] %}-->
<!--                <li class="nav-item dropdown">-->
<!--                    <a class="nav-link d-flex align-items-center" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--                        <img src="{{ session['user_picture'] }}" alt="Profile Picture" class="rounded-circle">-->
<!--                    </a>-->
<!--                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="profileDropdown">-->
<!--                        <a class="dropdown-item" href="#">-->
<!--                            <span class="icon"><i class="fas fa-user"></i></span>-->
<!--                            {{ session['user_name'] }}<br>{{ session['user_email'] }}-->
<!--                        </a>-->
<!--                        <div class="dropdown-divider"></div>-->
<!--                        <a class="dropdown-item" href="{{ url_for('auth_bp.logout') }}">-->
<!--                            <span class="icon"><i class="fas fa-sign-out-alt"></i></span>-->
<!--                            Log out-->
<!--                        </a>-->
<!--                    </div>-->
<!--                </li>-->
<!--                {% else %}-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{{ url_for('auth_bp.login') }}">Login</a>-->
<!--                </li>-->
<!--                {% endif %}-->
<!--            </ul>-->
<!--        </div>-->
<!--    </nav>-->

<!--    &lt;!&ndash; Include Bootstrap JS and dependencies (optional) &ndash;&gt;-->
<!--    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>-->
<!--    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>-->
<!--    <script src="https://kit.fontawesome.com/a076d05399.js"></script> &lt;!&ndash; Include FontAwesome for icons &ndash;&gt;-->
<!--</body>-->
<!--</html>-->